---
apiVersion: v1
kind: Template
objects:
- apiVersion: eunomia.kohls.io/v1alpha1
  kind: GitOpsConfig
  metadata:
    name: cakephp
    namespace: ${GITOPS_NAMESPACE}
  spec:
    templateSource:
      uri: ${GITOPS_REPO_URL}
      ref: ${GITOPS_REPO_REF}
      contextDir: ${GITOPS_REPO_DIR}
    triggers:
    - type: Change
    - type: Periodic
      cron: "${SCHEDULE}"
    serviceAccountRef: gitops-runner
    templateProcessorImage: ${TEMPLATE_PROCESSOR_IMAGE}
    resourceHandlingMode: None
    resourceDeletionMode: None
parameters:
- name: GITOPS_NAMESPACE
  value: cakephp-gitops
- name: GITOPS_REPO_URL
  value: https://github.com/xiangyugong/cakephp-ex
- name: GITOPS_REPO_REF
  value: master
- name: GITOPS_REPO_DIR
  value: ''
- name: TEMPLATE_PROCESSOR_IMAGE
  value: quay.io/kohlstechnology/eunomia-applier:v0.0.1
- name: SCHEDULE
  description: Periodic scheludle for gitops processing
  value: "@daily"
